import { CustomError } from 'ts-custom-error';
/**
 * The following error codes can be thrown by the dapp connector.
 */
export declare const ErrorCodes: {
    /** The dapp connector wasn't able to process the request */
    readonly InternalError: "InternalError";
    /** The user rejected the request */
    readonly Rejected: "Rejected";
    /** Can be thrown in various circumstances, e.g. one being a malformed transaction */
    readonly InvalidRequest: "InvalidRequest";
};
/**
 * ErrorCode type definition
 */
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
/**
 * Whenever there's a function called that returns a promise,
 * an error with the shape can be thrown.
 */
export declare class APIError extends CustomError {
    /** The code of the error that's thrown */
    code: ErrorCode;
    /** The reason the error is thrown */
    reason: string;
    constructor(code: ErrorCode, reason: string);
}
//# sourceMappingURL=errors.d.ts.map